//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_.Net_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Order_shop = new HashSet<Order_shop>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string img { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> discountprice { get; set; }
        public string describe { get; set; }
        public Nullable<int> sales { get; set; }
        public string type { get; set; }
        public string footstyle { get; set; }
        public Nullable<int> footstyle_id { get; set; }
        public string link { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual FoodStyle FoodStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_shop> Order_shop { get; set; }
    }
}
