//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_.Net_Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Navbar> Navbars { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
    }
}
