//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_.Net_Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Navbar> Navbars { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<OurStrength> OurStrengths { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Background> Backgrounds { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<ShopCart> ShopCarts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<UpcomingEvent> UpcomingEvents { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodStyle> FoodStyles { get; set; }
        public virtual DbSet<Order_shop> Order_shop { get; set; }
    }
}
