//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_.Net_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_shop
    {
        public int id { get; set; }
        public Nullable<int> foods_id { get; set; }
        public Nullable<int> users_id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> total_cart { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
    }
}
